---
created: 1326853478
livemode: false
id: evt_00000000000000
type: product.updated
object: event
request: 
pending_webhooks: 1
api_version: '2015-10-16'
data:
  object:
    id: prod_00000000000000
    object: product
    active: true
    attributes:
    - size
    - gender
    caption: 
    created: 1450089244
    description: Comfortable gray cotton t-shirts
    images: []
    livemode: false
    metadata: {}
    name: T-shirt
    package_dimensions: 
    shippable: true
    skus:
      object: list
      data: []
      has_more: false
      total_count: 0
      url: "/v1/skus?product=prod_7WxZfFDBhV0AJ0&active=true"
    updated: 1450089244
    url: 
  previous_attributes: 
